import type { ColorSchemeName } from 'react-native';

export type ThemeName = 'light' | 'navy';

export type AppTheme = {
  name: ThemeName;
  colors: {
    screen: string;
    heroBackground: string;
    heroBorder: string;
    heroIconBackground: string;
    heroIconBorder: string;
    heroStatBackground: string;
    heroStatBorder: string;
    heroStatPendingBackground: string;
    heroStatPendingBorder: string;
    heroStatInProgressBackground: string;
    heroStatInProgressBorder: string;
    heroStatDoneBackground: string;
    heroStatDoneBorder: string;
    tabBarBackground: string;
    tabBarBorder: string;
    tabButtonActive: string;
    tabTextInactive: string;
    panelBackground: string;
    cardBackground: string;
    subtleBackground: string;
    inputBackground: string;
    chipBackground: string;
    chipBorder: string;
    surfaceStrong: string;
    border: string;
    borderMuted: string;
    textPrimary: string;
    textSecondary: string;
    textMuted: string;
    textSoft: string;
    accent: string;
    accentText: string;
    categoryBackground: string;
    categoryText: string;
    pendingBadgeBackground: string;
    pendingBadgeBorder: string;
    pendingBadgeText: string;
    inProgressBadgeBackground: string;
    inProgressBadgeBorder: string;
    inProgressBadgeText: string;
    doneBadgeBackground: string;
    doneBadgeBorder: string;
    doneBadgeText: string;
    pendingButtonBackground: string;
    pendingButtonText: string;
    inProgressButtonBackground: string;
    inProgressButtonText: string;
    doneButtonBackground: string;
    doneButtonText: string;
    destructiveBackground: string;
    destructiveBorder: string;
    destructiveText: string;
    editButtonBackground: string;
    secondaryButtonBackground: string;
    secondaryButtonBorder: string;
    secondaryButtonText: string;
    monthButtonBackground: string;
    monthButtonBorder: string;
    todayPillBackground: string;
    todayPillBorder: string;
    filterResetBackground: string;
    filterResetBorder: string;
    filterChipInactiveBackground: string;
    filterChipInactiveBorder: string;
    helperBackground: string;
    modalBackground: string;
    modalBorder: string;
    modalBackdrop: string;
    permissionBackground: string;
    calendarCellBackground: string;
    calendarCellBorder: string;
    calendarSelectedBorder: string;
    calendarTodayBorder: string;
    calendarMutedText: string;
    placeholder: string;
    activityIndicator: string;
    iconSelected: string;
    iconUnselected: string;
  };
};

export const navyTheme: AppTheme = {
  name: 'navy',
  colors: {
    screen: '#0b1220',
    heroBackground: '#111827',
    heroBorder: '#1f2937',
    heroIconBackground: '#182131',
    heroIconBorder: '#293548',
    heroStatBackground: '#182131',
    heroStatBorder: '#293548',
    heroStatPendingBackground: '#182538',
    heroStatPendingBorder: '#334155',
    heroStatInProgressBackground: '#2b1d0f',
    heroStatInProgressBorder: '#92400e',
    heroStatDoneBackground: '#11261f',
    heroStatDoneBorder: '#166534',
    tabBarBackground: '#0f1728',
    tabBarBorder: '#202b3c',
    tabButtonActive: '#1f2937',
    tabTextInactive: '#9ca3af',
    panelBackground: '#1f2937',
    cardBackground: '#141d2d',
    subtleBackground: '#182131',
    inputBackground: '#121b2a',
    chipBackground: '#111827',
    chipBorder: '#374151',
    surfaceStrong: '#111827',
    border: '#2b3648',
    borderMuted: '#4b5563',
    textPrimary: '#f9fafb',
    textSecondary: '#d1d5db',
    textMuted: '#9ca3af',
    textSoft: '#94a3b8',
    accent: '#f59e0b',
    accentText: '#111827',
    categoryBackground: '#16325c',
    categoryText: '#dbeafe',
    pendingBadgeBackground: '#172554',
    pendingBadgeBorder: '#2563eb',
    pendingBadgeText: '#bfdbfe',
    inProgressBadgeBackground: '#451a03',
    inProgressBadgeBorder: '#f59e0b',
    inProgressBadgeText: '#fde68a',
    doneBadgeBackground: '#052e16',
    doneBadgeBorder: '#10b981',
    doneBadgeText: '#a7f3d0',
    pendingButtonBackground: '#334155',
    pendingButtonText: '#f9fafb',
    inProgressButtonBackground: '#f59e0b',
    inProgressButtonText: '#111827',
    doneButtonBackground: '#10b981',
    doneButtonText: '#052e16',
    destructiveBackground: '#25131a',
    destructiveBorder: '#5b2333',
    destructiveText: '#fca5a5',
    editButtonBackground: '#374151',
    secondaryButtonBackground: '#111827',
    secondaryButtonBorder: '#374151',
    secondaryButtonText: '#e5e7eb',
    monthButtonBackground: '#121b2a',
    monthButtonBorder: '#2a3648',
    todayPillBackground: '#121b2a',
    todayPillBorder: '#2a3648',
    filterResetBackground: '#111827',
    filterResetBorder: '#4b5563',
    filterChipInactiveBackground: '#111827',
    filterChipInactiveBorder: '#374151',
    helperBackground: '#141d2d',
    modalBackground: '#1f2937',
    modalBorder: '#374151',
    modalBackdrop: 'rgba(17, 24, 39, 0.72)',
    permissionBackground: '#141d2d',
    calendarCellBackground: '#141d2d',
    calendarCellBorder: '#2b3648',
    calendarSelectedBorder: '#d97706',
    calendarTodayBorder: '#fbbf24',
    calendarMutedText: '#6b7280',
    placeholder: '#6b7280',
    activityIndicator: '#f59e0b',
    iconSelected: '#f59e0b',
    iconUnselected: '#9ca3af',
  },
};

export const lightTheme: AppTheme = {
  name: 'light',
  colors: {
    screen: '#f4f6f8',
    heroBackground: '#ffffff',
    heroBorder: '#dce4ec',
    heroIconBackground: '#edf2f7',
    heroIconBorder: '#d5dee8',
    heroStatBackground: '#ffffff',
    heroStatBorder: '#d8e1ea',
    heroStatPendingBackground: '#eef4fa',
    heroStatPendingBorder: '#c9d6e5',
    heroStatInProgressBackground: '#fff4de',
    heroStatInProgressBorder: '#f4c365',
    heroStatDoneBackground: '#e9f8ef',
    heroStatDoneBorder: '#8ad0a5',
    tabBarBackground: '#ffffff',
    tabBarBorder: '#dce4ec',
    tabButtonActive: '#e9eff6',
    tabTextInactive: '#6b7c8e',
    panelBackground: '#ffffff',
    cardBackground: '#ffffff',
    subtleBackground: '#f6f9fc',
    inputBackground: '#ffffff',
    chipBackground: '#f8fafc',
    chipBorder: '#d6dee8',
    surfaceStrong: '#edf2f7',
    border: '#d6dee8',
    borderMuted: '#c4d0dc',
    textPrimary: '#142031',
    textSecondary: '#475569',
    textMuted: '#64748b',
    textSoft: '#7c8da0',
    accent: '#d97706',
    accentText: '#111827',
    categoryBackground: '#e5eef8',
    categoryText: '#1d4ed8',
    pendingBadgeBackground: '#dbeafe',
    pendingBadgeBorder: '#93c5fd',
    pendingBadgeText: '#1d4ed8',
    inProgressBadgeBackground: '#fef3c7',
    inProgressBadgeBorder: '#f59e0b',
    inProgressBadgeText: '#92400e',
    doneBadgeBackground: '#dcfce7',
    doneBadgeBorder: '#4ade80',
    doneBadgeText: '#166534',
    pendingButtonBackground: '#e2e8f0',
    pendingButtonText: '#334155',
    inProgressButtonBackground: '#fde68a',
    inProgressButtonText: '#92400e',
    doneButtonBackground: '#bbf7d0',
    doneButtonText: '#166534',
    destructiveBackground: '#fee2e2',
    destructiveBorder: '#fca5a5',
    destructiveText: '#b91c1c',
    editButtonBackground: '#e2e8f0',
    secondaryButtonBackground: '#ffffff',
    secondaryButtonBorder: '#d6dee8',
    secondaryButtonText: '#334155',
    monthButtonBackground: '#ffffff',
    monthButtonBorder: '#d6dee8',
    todayPillBackground: '#edf2f7',
    todayPillBorder: '#d6dee8',
    filterResetBackground: '#ffffff',
    filterResetBorder: '#c4d0dc',
    filterChipInactiveBackground: '#f8fafc',
    filterChipInactiveBorder: '#d6dee8',
    helperBackground: '#f8fafc',
    modalBackground: '#ffffff',
    modalBorder: '#d6dee8',
    modalBackdrop: 'rgba(15, 23, 42, 0.25)',
    permissionBackground: '#f8fafc',
    calendarCellBackground: '#ffffff',
    calendarCellBorder: '#d6dee8',
    calendarSelectedBorder: '#d97706',
    calendarTodayBorder: '#fbbf24',
    calendarMutedText: '#94a3b8',
    placeholder: '#94a3b8',
    activityIndicator: '#d97706',
    iconSelected: '#d97706',
    iconUnselected: '#64748b',
  },
};

export function getAppTheme(colorScheme: ColorSchemeName): AppTheme {
  return colorScheme === 'dark' ? navyTheme : lightTheme;
}
